version: '3.7'
services:
  everything:
    container_name: python-playground-everything
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/python-playground
    command: ['./entrypoint.sh', 'birthday-paradox']
